caffe_tools: '/Users/MelRod/lib/caffe-master/build/tools/'
config_dir: '/Users/MelRod/myProjects/GPIS_data/caffe_config/'
caffe_model: '/Users/MelRod/myProjects/GPIS_data/caffe_config/caffenet.caffemodel'
caffe_finetuning_model: '/Users/MelRod/myProjects/GPIS_data/caffe_config/alexnet.caffemodel'

portion_training: 0.75
deploy_mode: 'cpu'
batch_size: 1000
vector_merging_method: 'mean'