# Configuration yaml file for chessboard registration

# Load previous data toggle
load: False 

# Chessboard dimensions
sx: 6
sy: 9

# Angle of the table to the world reference in degrees
table_angle: 27.5

# Rotation and translation save directory
save_dir: 'data/calibration/'

# Number of depth images
num_images: 1

# Figure plotting
scale_amt: 10.0
