# Configuration yaml file for chessboard registration

# Load previous data toggle
load: False 

# Chessboard dimensions
sx: 6
sy: 9

# Angle of the table to the world reference in degrees
table_angle: 27

# Rotation and translation save directory
save_dir: 'data/calibration/'

# Number of depth images
num_images: 1

# Number of separate calibrations to average
num_avg: 20

# Thickness of chessboard
chessboard_thickness: 0.004

# Figure plotting
scale_amt: 10.0

# Debugging on or off
debug: 0