path_to_mayapy: '/Applications/Autodesk/maya2016/Maya.app/Contents/bin/mayapy'

database_dir: '/Users/MelRod/myProjects/GPIS_data/data'
mesh_database_id: 'SHREC'
mesh_database_index: '/Users/MelRod/myProjects/GPIS_data/Cat50_ModelDatabase/index.db'
portion_training: 1.0