path_to_mayapy: '/Applications/Autodesk/maya2014/Maya.app/Contents/bin/mayapy'

dest_dir: '/Users/MelRod/myProjects/GPIS_data/rendered_sets/YCB'
mesh_dir: '/Users/MelRod/myProjects/GPIS_data/YCB'

render_type: 'color' # or depth
back_color:
 r: 0.0
 g: 0.0
 b: 0.0
num_radial: 2
num_lat: 5
num_long: 5
