# Core parameters ####################################################
!include partials/paths_rll4_jeff.yaml
#!include partials/paths_gce.yaml
cache_dir:    /home/jmahler/jeff_working/GPIS/data/gcs

dataset_counts: data/counts.txt
datasets:
  - SHREC14LSGTB
max_chunk_size: 1
num_trials: 0
sleep_time: 10

priors_dataset: keys_10000_train_and_val
priors_feature_names:
  - nearest_features_1000_train_and_val

# Will be overridden by startup script
dataset:     SHREC14LSGTB
chunk_start: 0
chunk_end:   8980

# Experiment parameters ##############################################
!include partials/experiment_params.yaml
!include partials/bandit_params.yaml
!include partials/window_params.yaml

# Window weights #####################################################
inf:   &id_inf       100000000000000000000.0
zero:  &id_zero      0.0
weight_proj_win:     0.0
weight_grad_x:       gaussian_500.0_1.75
weight_grad_y:       gaussian_500.0_1.75
weight_curvature:    0.0
weight_grasp_center: 0.0
weight_grasp_axis:   0.0
weight_grasp_angle:  0.0
weight_gravity:      200.0

# Kernel params
kernel_sigma: 1.0
kernel_l: 1.0
kernel_tolerance: 0.001

prior_neighbor_weight: 0.001
prior_neighbor_distance: 20
prior_num_neighbors: 0
prior_kernel_tolerance: 0.001

lb_alpha: 0.50

# Retrieval params
retrieval:
  train_pct: 0.75
  num_components: 100
  num_neighbors: 5
  train_extraction_method: full
  train_num_images: 50
  test_extraction_methods:
    - subset
    - subset
    - subset
    - subset
    - subset
    - subset
  test_num_images:
    - 1
    - 2
    - 5
    - 10
    - 25
    - 50

# Caffe configuration
caffe:
  caffe_tools: '/home/jmahler/Libraries/caffe/build/tools/'
  config_dir: '/home/jmahler/mel/GPIS_data/caffe_data/'
  caffe_model: 'caffenet.caffemodel'
  caffe_finetuning_model: 'alexnet.caffemodel'
  deploy_file: 'deploy.prototxt'
  mean_file: 'mean.npy'

  portion_training: 1.00
  deploy_mode: 'gpu'
  batch_size: 10
  pooling_method: 'mean'

  rendered_image_ext: '.jpg'
  rendered_image_dir: '/home/jmahler/mel/GPIS_data/rendered_sets/all'

  images_per_object: 50
  raw_scale: 255
  image_dim_x: 256
  image_dim_y: 256

# Params to run over
param_values:
  moment:
      - 50
      - 150
  num_nearest:
      - 10
  nn_weight:
      - 0.001

# Post-experiment parameters #########################################
!include partials/plot_params.yaml

# GCE parameters #####################################################
client_secrets: &id_client_secrets client_secrets.json
oauth_storage:  &id_oauth_storage  oauth2.dat
disk_type:      &id_disk_type      PERSISTENT
num_processes: 8
project:        nth-clone-620
bucket:          dex-net-results-2 # TODO
compute:
  project:        &id_project        nth-clone-620
  bucket:         &id_bucket         dex-net-results-2 # TODO
  api_version:    v1
  machine_type:   n1-standard-1
  disk_size_gb: 2048
  zones:
    - asia-east1-a
    - us-central1-a
    - europe-west1-b
  instance_quota: 200
  startup_script: scripts/cm_startup.sh # TODO
  image_project:  *id_project
  image:          dex-net-image
  data_disks:
    - dex-net-data-2-big-asia
    - dex-net-data-2-big
    - dex-net-data-2-big-europe
  service_email:  default
  network:        default
  run_script:     src/grasp_selection/correlated_bandits_priors.py
  results_script: src/grasp_selection/compile_bandit_prior_results.py
  update_script: src/grasp_selection/compile_bandit_prior_results.py
  scopes:
    - https://www.googleapis.com/auth/compute
    - https://www.googleapis.com/auth/devstorage.full_control
    - https://www.googleapis.com/auth/devstorage.read_only
    - https://www.googleapis.com/auth/devstorage.read_write

# Notification parameters ############################################
gmail_user:     &id_gmail_user      RavenDebridement
gmail_password: &id_gmail_password  surgicallab
notify_email:   &id_notify_email    jmahl42@gmail.com
